version: "3.9"

services:
  web:
    image: atekcr.azurecr.io/azure-web-api:${TAG}
    deploy: 
      replicas: 2
    ports:
      - "7000:80"

  app-server: 
    image: atekcr.azurecr.io/app-server-nginx:${TAG}
    deploy: 
      replicas: 2
    ports: 
      - "80:80"

    