version: "3.9"

services:
  web:
    image: atekcr.azurecr.io/azure-web-api:${TAG}
    deploy: 
      replicas: 2
    ports:
      - "0.0.0.0:7000:80"
      - ":::7000:80"
    networks: 
      - services

  app-server: 
    image: atekcr.azurecr.io/app-server-nginx:${TAG}
    deploy: 
      replicas: 2
    ports: 
      - "0.0.0.0:80:80"
      - ":::80:80"
    networks: 
      - services
    depends_on: 
      - web

networks:
  services:
    driver: overlay

      
    