version: "3.9"

services:
  nginx: 
    image: atekcr.azurecr.io/nginx:${TAG}
    deploy: 
      replicas: 2
    ports: 
      - 80:80
    networks: 
      - backend
      
networks: 
  backend:
    driver: overlay