version: "3.9"

services:
  app-server: 
    image: app-server:${TAG}
    deploy: 
      replicas: 2
    ports: 
      - 80:80
    networks: 
      - backend
      
networks: 
  backend:
    driver: overlay