version: "3.9"

services:
  api:
    image: atekcr.azurecr.io/customers-api:${TAG}
    deploy: 
      replicas: 2
    ports:
      - 7000:80
    networks: 
      backend:
        aliases: 
          - customers-api