version: "3.9"

services:
  customers-api:
    image: atekcr.azurecr.io/customers-api:${TAG}
    deploy: 
      replicas: 2
    ports:
      - 7000:80
    networks: 
      - backend

networks: 
  backend:
    driver: overlay