name: build-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - run: |
          docker build ./azure-web-api -t azure-web-api:${{ github.run_number }}
        shell: bash

  release:
    runs-on: self-hosted
    needs: build
    environment:
      name: spot-env
      url: http://bd971d6ccc4e4a788bb891882550d501.brazilsouth.cloudapp.azure.com/WeatherForecast
    steps:
      - run: |
          docker stop azure-web-api && docker rm azure-web-api
          docker run -d -p 80:80 --name azure-web-api azure-web-api:${{ github.run_number }}
        shell: bash

