name: build-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - run: |
          docker build ./azure-web-api -t atekcr.azurecr.io/azure-web-api:${{ github.run_number }}
          docker push atekcr.azurecr.io/azure-web-api:${{ github.run_number }}
        shell: bash

  release:
    runs-on: self-hosted
    needs: build
    environment:
      name: spot-env
      url: http://bd971d6ccc4e4a788bb891882550d501.brazilsouth.cloudapp.azure.com/WeatherForecast
    steps:
      - run: |
          docker stack deploy --with-registry-auth --compose-file docker-compose.yml azure-web-api
        shell: bash
        env:
          TAG: ${{ github.run_number }}

