name: build-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "checkout repository"
        uses: actions/checkout@main

      - run: |
          docker build ./azure-web-api -t customers-api:${{ github.run_number }}
          #docker push customers-api:${{ github.run_number }}
        name: build customers-api

      - run: |
          docker build ./app-server -t app-server:${{ github.run_number }}
          #docker push app-server:${{ github.run_number }}
        name: build app-server

  release:
    runs-on: self-hosted
    needs: build
    environment:
      name: spot-env
    steps:
      - run: |
          docker stack deploy --with-registry-auth --compose-file ./azure-web-api/docker-compose.yml app
          docker stack deploy --with-registry-auth --compose-file ./app-server/docker-compose.yml app
        shell: bash
        env:
          TAG: ${{ github.run_number }}

