name: build-release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "checkout repository"
        uses: actions/checkout@main

      - run: |
          docker build ./azure-web-api -t atekcr.azurecr.io/customers-api:${{ github.run_number }}
          docker push atekcr.azurecr.io/customers-api:${{ github.run_number }}
        name: build customers-api

      - run: |
          docker build ./app-server -t atekcr.azurecr.io/nginx:${{ github.run_number }}
          docker push atekcr.azurecr.io/nginx:${{ github.run_number }}
        name: build nginx

  release:
    runs-on: self-hosted
    needs: build
    environment:
      name: spot-env
    steps:
      - run: |
          docker stack deploy --with-registry-auth --compose-file ./azure-web-api/docker-compose.yml
          docker stack deploy --with-registry-auth --compose-file ./app-server/docker-compose.yml
        shell: bash
        env:
          TAG: ${{ github.run_number }}

